[Kyu] 계산기 클론앱
DeveloperAcademy-POSTECH/ReviewWQuestion-Calculator pull request #18
Opened 2022-06-01 15:42 UTC by kyustudyo

# 작업 내용
### - 0 버튼 길게 구현
### - 등호를 누르면 이전에 입력된 연산자로 계속 연산 수행

# 고민한 내용
### **Custom VIewModifier**를 만들어서 View에 적용해서 코드길이를 줄여봤습니다.

# 구현 못한 것
### - 4자리로 갈경우 쉼표 표시
### - 소수점 버튼
### - 자연상수 표시 구현 
### - 사칙연산 우선순위 구현
### - 주석정리 또는 제거 
### - 클린한 코드(인덴트, 프로퍼티, 메서드 이름등)

# 리뷰 받고 싶은 내용 (질문할 내용)
### <함수가독성>
```Swift
class Logic : ObservableObject 
```
### 에 많은 함수가 있습니다. 하나의 함수에 '한가지' 기능을 넣으라는 글을 읽었습니다. 이번 프로젝트에서 하려고했지만, 실력과 시간이 부족해 구현하지 못했습니다. 한 가지 기능을 하는 함수를 잘 작성하는 팁이있을까요?

2022-06-02 00:45 UTC, YebinKim requested changes
@kyustudyo 
규~ 아래 내용을 포함해서 작성 부탁드려요!

- 작업 내용
- 고민한 내용
- 리뷰 받고 싶은 내용 (질문할 내용)

2022-06-03 11:13 UTC, kyustudyo commented
> @kyustudyo 규~ 아래 내용을 포함해서 작성 부탁드려요!
> 
> * 작업 내용
> * 고민한 내용
> * 리뷰 받고 싶은 내용 (질문할 내용)

@YebinKim 안녕하세요~ 혹시 re-request review를 눌러야 할까요?

2022-06-04 06:28 UTC, jayden000106 commented on SwiftUI/ReviewWQuestion-Calculator/Buttons/LongButton.swift
> +
어떤 의도로 5칸을 띄우셨나요??

2022-06-04 06:54 UTC, Rookie0031 commented on SwiftUI/ReviewWQuestion-Calculator/Logic.swift
> +        if checkComponent(component) == "C" || checkComponent(component) == "AC"{
checkComponent 함수 내부에 if가 많이 쓰이는 느낌인데 switch case로 바꿔보시는것은 어떨까요??

2022-09-12 12:30 UTC, Rookie0031 approved these changes
## Approved
규 갑작스러운 풀리퀘 무엇??

2022-09-12 13:18 UTC, kyustudyo commented
> ## Approved
> 규 갑작스러운 풀리퀘 무엇??

2022-09-12 13:18 UTC, closed without merging